# Generated by Django 4.2.7 on 2023-11-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('idade', models.BigIntegerField()),
                ('raca', models.CharField(max_length=10)),
                ('altura', models.FloatField()),
            ],
        ),
    ]
